intelligence:
  policy:
    min_confidence: 0.75
    min_calibration: 0.96
    fairness_delta_max: 0.02
    require_explanations: false
  
  router:
    hybrid_weights: 
      latency: 0.3
      quality: 0.7
    allow_shadow: true
    canary_pct_default: 10
    max_specialists_per_task: 5
    auto_detect_confidence_threshold: 0.8
  
  ensembler:
    type: "stack"
    meta_model: "lr-meta@1.0.2"
    uncertainty_methods: ["calibration", "variance", "entropy"]
    min_samples_for_training: 100
    calibration_method: "platt"
    ensemble_weights: "adaptive"
  
  inference:
    timeout_ms: 800
    batch_max: 64
    retry_attempts: 2
    canary_auto_promote_threshold: 0.95
    shadow_agreement_threshold: 0.90
    policy_enforcement: true
  
  planner:
    max_concurrent_plans: 100
    plan_timeout_seconds: 300
    enable_preflight_checks: true
    default_log_level: "summary"
  
  governance:
    require_approval_for_high_risk: true
    auto_approve_low_risk: true
    policy_cache_ttl_seconds: 300
  
  monitoring:
    metrics_retention_hours: 168  # 7 days
    alert_on_policy_violations: true
    performance_degradation_threshold: 0.1
    
  deployment:
    canary_steps: [5, 25, 50, 100]
    shadow_traffic_percentage: 10
    rollback_on_failure: true
    
  specialists:
    # ML/DL Specialists (21 total)
    - name: "tabular_classification"
      models: ["xgb@1.3.2", "rf@2.0.1", "lgb@1.1.0"]
      weight: 1.0
    - name: "deep_classification" 
      models: ["neural_net@2.1.0", "dnn@1.5.0"]
      weight: 0.9
    - name: "ensemble_classifier"
      models: ["ensemble_classifier_model@1.0.0"]
      weight: 1.1
    - name: "bayesian_classifier"
      models: ["naive_bayes@1.0.0", "gaussian_nb@1.2.0"]
      weight: 0.8
    - name: "meta_classifier"
      models: ["meta_learner@1.0.0"]
      weight: 1.2
    - name: "linear_regression"
      models: ["lr@1.0.1", "ridge@1.1.0", "lasso@1.1.0"]
      weight: 1.0
    - name: "tree_regression"
      models: ["random_forest@2.0.1", "gbm@1.2.0"]
      weight: 1.0
    - name: "neural_regression"
      models: ["mlp_regressor@1.0.0", "dnn_reg@1.1.0"]
      weight: 0.9
    - name: "gaussian_process"
      models: ["gp@1.0.0"]
      weight: 0.7
    - name: "bayesian_regression"
      models: ["bayesian_ridge@1.0.0"]
      weight: 0.8
    - name: "kmeans_specialist"
      models: ["kmeans@1.0.0"]
      weight: 1.0
    - name: "hierarchical_specialist"
      models: ["agglomerative@1.0.0"]
      weight: 0.9
    - name: "density_specialist"
      models: ["dbscan@1.0.0"]
      weight: 0.8
    - name: "spectral_specialist"
      models: ["spectral_clustering@1.0.0"]
      weight: 0.7
    - name: "mixture_model_specialist"
      models: ["gmm@1.0.0"]
      weight: 0.8
    - name: "transformer_nlp"
      models: ["bert-base@1.2.0", "roberta@1.1.0"]
      weight: 1.2
    - name: "cnn_vision"
      models: ["resnet50@1.1.0", "efficientnet@1.0.0"]
      weight: 1.1
    - name: "lstm_timeseries"
      models: ["lstm_model@1.0.5", "gru@1.0.0"]
      weight: 1.0
    - name: "prophet_specialist"
      models: ["prophet@1.0.0"]
      weight: 0.9
    - name: "dqn_specialist"
      models: ["dqn_agent@0.9.2"]
      weight: 1.0
    - name: "policy_gradient_specialist"
      models: ["pg_agent@1.0.0"]
      weight: 1.0