# Golden SLOs & Prometheus Alert Rules

# Example SLOs (Prometheus)
# 99.9% API availability
record: api_availability
expr: sum(rate(http_server_requests_total{status!~"5.."}[5m])) / sum(rate(http_server_requests_total[5m]))

# 99% worker job success
record: worker_job_success
expr: sum(rate(grace_worker_tasks_total{status="success"}[5m])) / sum(rate(grace_worker_tasks_total[5m]))

# 95% p50 latency < 500ms
record: api_p50_latency
expr: histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))

# Example Alert Rules
- alert: APIAvailabilityLow
  expr: api_availability < 0.999
  for: 10m
  labels:
    severity: page
  annotations:
    summary: "API availability below SLO"

- alert: WorkerJobSuccessLow
  expr: worker_job_success < 0.99
  for: 10m
  labels:
    severity: page
  annotations:
    summary: "Worker job success below SLO"

- alert: APILatencyHigh
  expr: api_p50_latency > 0.5
  for: 10m
  labels:
    severity: page
  annotations:
    summary: "API p50 latency above SLO"

# Save as monitoring/prometheus_slos_alerts.yml and load in Prometheus config.
