"""Initial Grace system models

Revision ID: 6046a445fabc
Revises: 
Create Date: 2025-09-28 19:23:01.392363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6046a445fabc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_data', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_tasks'))
    )
    op.create_index(op.f('ix_background_tasks_priority'), 'background_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_background_tasks_status'), 'background_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_background_tasks_task_type'), 'background_tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_scheduled_at', 'background_tasks', ['scheduled_at'], unique=False)
    op.create_index('ix_tasks_status_priority', 'background_tasks', ['status', 'priority'], unique=False)
    op.create_index('ix_tasks_task_type', 'background_tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_worker_id', 'background_tasks', ['worker_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_last_login', 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('binary_content', sa.LargeBinary(), nullable=True),
    sa.Column('memory_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('compression_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)
    op.create_index('ix_memories_content_hash', 'memories', ['content_hash'], unique=False)
    op.create_index('ix_memories_expires_at', 'memories', ['expires_at'], unique=False)
    op.create_index('ix_memories_last_accessed', 'memories', ['last_accessed'], unique=False)
    op.create_index('ix_memories_memory_type', 'memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memories_priority'), 'memories', ['priority'], unique=False)
    op.create_index('ix_memories_user_id_created_at', 'memories', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_memories_user_id_key', 'memories', ['user_id', 'key'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_last_accessed', 'sessions', ['last_accessed'], unique=False)
    op.create_index(op.f('ix_sessions_token_id'), 'sessions', ['token_id'], unique=True)
    op.create_index('ix_sessions_user_id_created_at', 'sessions', ['user_id', 'created_at'], unique=False)
    op.create_table('system_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('operation_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_system_operations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_operations'))
    )
    op.create_index('ix_operations_created_at', 'system_operations', ['created_at'], unique=False)
    op.create_index('ix_operations_resource', 'system_operations', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_operations_type_status', 'system_operations', ['operation_type', 'status'], unique=False)
    op.create_index('ix_operations_user_id_created_at', 'system_operations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_operations_operation_type'), 'system_operations', ['operation_type'], unique=False)
    op.create_index(op.f('ix_system_operations_resource_id'), 'system_operations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_system_operations_resource_type'), 'system_operations', ['resource_type'], unique=False)
    op.create_index(op.f('ix_system_operations_status'), 'system_operations', ['status'], unique=False)
    op.create_table('memory_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_memory_embeddings_memory_id_memories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_embeddings'))
    )
    op.create_index('ix_memory_embeddings_chunk', 'memory_embeddings', ['memory_id', 'chunk_index'], unique=False)
    op.create_index('ix_memory_embeddings_memory_id', 'memory_embeddings', ['memory_id'], unique=False)
    op.create_index('ix_memory_embeddings_model', 'memory_embeddings', ['embedding_model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_embeddings_model', table_name='memory_embeddings')
    op.drop_index('ix_memory_embeddings_memory_id', table_name='memory_embeddings')
    op.drop_index('ix_memory_embeddings_chunk', table_name='memory_embeddings')
    op.drop_table('memory_embeddings')
    op.drop_index(op.f('ix_system_operations_status'), table_name='system_operations')
    op.drop_index(op.f('ix_system_operations_resource_type'), table_name='system_operations')
    op.drop_index(op.f('ix_system_operations_resource_id'), table_name='system_operations')
    op.drop_index(op.f('ix_system_operations_operation_type'), table_name='system_operations')
    op.drop_index('ix_operations_user_id_created_at', table_name='system_operations')
    op.drop_index('ix_operations_type_status', table_name='system_operations')
    op.drop_index('ix_operations_resource', table_name='system_operations')
    op.drop_index('ix_operations_created_at', table_name='system_operations')
    op.drop_table('system_operations')
    op.drop_index('ix_sessions_user_id_created_at', table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_id'), table_name='sessions')
    op.drop_index('ix_sessions_last_accessed', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_memories_user_id_key', table_name='memories')
    op.drop_index('ix_memories_user_id_created_at', table_name='memories')
    op.drop_index(op.f('ix_memories_priority'), table_name='memories')
    op.drop_index('ix_memories_memory_type', table_name='memories')
    op.drop_index('ix_memories_last_accessed', table_name='memories')
    op.drop_index('ix_memories_expires_at', table_name='memories')
    op.drop_index('ix_memories_content_hash', table_name='memories')
    op.drop_index(op.f('ix_memories_category'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_last_login', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tasks_worker_id', table_name='background_tasks')
    op.drop_index('ix_tasks_task_type', table_name='background_tasks')
    op.drop_index('ix_tasks_status_priority', table_name='background_tasks')
    op.drop_index('ix_tasks_scheduled_at', table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_task_type'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_status'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_priority'), table_name='background_tasks')
    op.drop_table('background_tasks')
    # ### end Alembic commands ###
