from dataclasses import dataclass, asdict
from typing import Dict, Any

@dataclass
class KernelInsight:
    """Represents a piece of knowledge or an observation generated by a kernel."""
    source_kernel: str
    insight_type: str
    content: str
    confidence: float
    timestamp: float = 0.0  # Will be set at creation

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
