# Grace TriggerMesh - Event routing configuration

# Version and metadata
version: "1.0"
mesh_id: "grace-primary"
description: "Grace event routing mesh configuration"

# Default settings
defaults:
  ttl_seconds: 300
  priority: "normal"
  retry_enabled: true
  max_retries: 3

# Route definitions
routes:
  # Memory operations
  - name: "memory_writes"
    pattern: "memory.write"
    targets:
      - "analytics_kernel"
      - "audit_logger"
    filters:
      - type: "trust_threshold"
        threshold: 0.5
    actions:
      - type: "log"
        level: "info"
      - type: "metric"
        name: "memory_writes_total"
  
  - name: "memory_pattern_learned"
    pattern: "memory.pattern.*"
    targets:
      - "mldl_kernel"
      - "governance_validator"
    priority: "high"
  
  # Kernel heartbeats
  - name: "kernel_heartbeats"
    pattern: "kernel.heartbeat"
    targets:
      - "health_monitor"
      - "resilience_kernel"
    filters:
      - type: "source_in"
        sources: ["multi_os_kernel", "mldl_kernel", "resilience_kernel"]
  
  # Governance escalations
  - name: "governance_escalations"
    pattern: "resilience.escalation"
    targets:
      - "governance_committee"
      - "security_team"
      - "audit_logger"
    priority: "critical"
    actions:
      - type: "alert"
        channel: "slack"
      - type: "log"
        level: "warning"
  
  # Trust attestations
  - name: "trust_updates"
    pattern: "trust.update"
    targets:
      - "trust_dashboard"
      - "audit_logger"
    filters:
      - type: "trust_change_significant"
        threshold: 0.1
  
  # System errors
  - name: "system_errors"
    pattern: "system.error"
    targets:
      - "resilience_kernel"
      - "error_handler"
      - "audit_logger"
    priority: "high"
    actions:
      - type: "alert"
        channel: "pagerduty"
  
  # Inference requests/responses
  - name: "mldl_inference"
    pattern: "mldl.infer"
    targets:
      - "mldl_kernel"
    timeout_seconds: 30
  
  - name: "mldl_responses"
    pattern: "mldl.infer.response"
    targets: []  # Handled by correlation_id
  
  # Kernel commands
  - name: "kernel_commands"
    pattern: "kernel.command"
    targets:
      - "multi_os_kernel"
    filters:
      - type: "authorized"
        required_role: "admin"

# Subscriptions (automatic binding on startup)
subscriptions:
  - subscriber: "audit_logger"
    patterns:
      - "memory.write"
      - "system.error"
      - "resilience.escalation"
      - "trust.update"
  
  - subscriber: "health_monitor"
    patterns:
      - "kernel.heartbeat"
      - "kernel.failure"
      - "system.error"
  
  - subscriber: "analytics_kernel"
    patterns:
      - "memory.write"
      - "memory.pattern.*"
      - "mldl.infer.response"
  
  - subscriber: "governance_validator"
    patterns:
      - "memory.pattern.*"
      - "system.error"
      - "resilience.escalation"

# Dead letter queue configuration
dlq:
  enabled: true
  max_size: 1000
  retention_seconds: 86400
  routes:
    - pattern: "*.failed"
      target: "dlq_processor"

# Metrics and observability
metrics:
  enabled: true
  export_interval_seconds: 60
  labels:
    - "event_type"
    - "source"
    - "priority"

# Circuit breaker configuration
circuit_breaker:
  enabled: true
  failure_threshold: 5
  timeout_seconds: 60
  half_open_requests: 3
