# Grace Ingress Kernel - Configuration Example

# Default configuration values for the Ingress Kernel
# This shows the complete configuration structure and default values

ingress:
  # Validation policies
  validation:
    min_validity: 0.80        # Minimum schema validity score (0.0-1.0)
    min_trust: 0.70          # Minimum trust score for processing (0.0-1.0)
    block_on_pii: true       # Block processing if PII detected with block policy
    
  # Deduplication settings
  dedupe:
    threshold: 0.87          # Content similarity threshold for deduplication
    strategy: "hash+fuzzy"   # Deduplication strategy
    
  # Enrichment configuration
  enrichment:
    ner_model: "ner.en@2.4.1"         # Named Entity Recognition model
    embeddings: "text-encoder@1.1.0"   # Text embedding model
    enable_geocoding: true              # Enable location enrichment
    enable_topic_extraction: true      # Enable topic extraction
    
  # Publishing configuration
  publish:
    topics:
      - "articles.v1"        # Article topic for messaging
      - "transcripts.v1"     # Transcript topic for messaging
      - "tabular.v1"         # Tabular data topic for messaging
      
  # Governance defaults
  governance:
    retention_days_default: 365    # Default retention period (days)
    label_default: "internal"      # Default governance classification
    max_retention_days: 2555       # Maximum allowed retention (~7 years)
    
  # Trust scoring weights
  trust_weights:
    w1: 0.25    # source_reputation weight
    w2: 0.20    # schema_compliance weight 
    w3: 0.15    # parser_confidence weight
    w4: 0.20    # cross_source_agreement weight
    w5: 0.10    # freshness_factor weight
    w6: 0.10    # pii_risk weight (subtracted)
    
  # Storage configuration
  storage:
    base_path: "/var/lib/grace/ingress"
    bronze_path: "bronze"      # Raw events storage
    silver_path: "silver"      # Normalized records storage  
    gold_path: "gold"          # Curated features storage
    
  # Health monitoring
  monitoring:
    health_check_interval: 60    # Health check interval (seconds)
    metrics_retention_days: 90   # Metrics retention period
    
  # Snapshot management
  snapshots:
    auto_interval_hours: 6       # Automatic snapshot interval
    max_snapshots: 100          # Maximum snapshots to keep
    storage_path: "snapshots"    # Snapshot storage path
    
# Source-specific configuration examples
sources:
  # Example RSS source
  news_rss_example:
    kind: rss
    uri: "https://example.com/news.xml"
    auth_mode: none
    schedule: "0 * * * *"       # Every hour
    parser: xml
    parser_opts:
      extract_full_text: true
      follow_links: false
    target_contract: "contract:article.v1"
    retention_days: 180
    pii_policy: mask
    governance_label: public
    enabled: true
    
  # Example API source  
  api_data_example:
    kind: http
    uri: "https://api.company.com/v1/data"
    auth_mode: bearer
    secrets_ref: "api_bearer_token_secret"
    schedule: "*/15 * * * *"    # Every 15 minutes
    parser: json
    parser_opts:
      flatten_nested: true
      max_depth: 3
    target_contract: "contract:tabular.v1"
    retention_days: 365
    pii_policy: hash
    governance_label: internal
    enabled: true
    
  # Example S3 source
  s3_uploads_example:
    kind: s3
    uri: "s3://data-bucket/uploads/"
    auth_mode: aws_iam
    schedule: "stream"          # Continuous monitoring
    parser: pdf
    parser_opts:
      extract_images: false
      ocr_enabled: true
    target_contract: "contract:article.v1"
    retention_days: 1095        # 3 years
    pii_policy: allow_with_consent
    governance_label: restricted
    enabled: false              # Disabled by default for restricted sources

# Database configuration
database:
  connection_string: "mysql://user:pass@localhost/grace_ingress"
  max_connections: 20
  connection_timeout: 30
  
# Event Bus configuration  
event_bus:
  kafka_brokers: ["localhost:9092"]
  topics:
    ingress_events: "grace.ingress.events"
    governance_events: "grace.governance.events"
    mlt_events: "grace.mlt.events"
    
# Bridge configurations
bridges:
  # Event Mesh Bridge
  mesh:
    enabled: true
    routing_rules:
      SOURCE_REGISTERED: ["governance", "audit"]
      CAPTURED_RAW: ["audit", "monitoring"]
      NORMALIZED: ["specialists", "feature_store"]
      VALIDATION_FAILED: ["governance", "alert_manager"]
      PERSISTED: ["audit", "data_catalog"]
      
  # Governance Bridge  
  governance:
    enabled: true
    auto_approve_low_risk: true
    require_approval_for:
      - restricted_sources
      - high_pii_risk
      - external_sources
      
  # MLT Bridge
  mlt:
    enabled: true
    experience_buffer_size: 1000
    emit_interval_seconds: 30
    adaptation_plan_polling_interval: 60

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: file
      filename: "/var/log/grace/ingress.log"
      max_size_mb: 100
      backup_count: 5
    - type: console
      
# Security settings
security:
  secrets_backend: "vault"     # vault, env, or file
  vault_url: "https://vault.company.com"
  encryption_key_rotation_days: 90
  
# Performance tuning
performance:
  max_concurrent_jobs: 10
  processing_timeout_seconds: 300
  batch_size: 100
  memory_limit_mb: 2048