openapi: 3.0.3
info:
  title: Grace Governance Kernel API
  version: 1.0.0
  description: |
    Production-ready OpenAPI specification for the Grace Governance Kernel.
    Includes endpoints for governance requests, health checks, metrics, and audit trail access.
servers:
  - url: http://localhost:8000
paths:
  /governance/request:
    post:
      summary: Process a governance request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: policy
                payload:
                  type: object
                  example: { claims: [], context: {} }
      responses:
        '200':
          description: Governance decision result
          content:
            application/json:
              schema:
                type: object
                properties:
                  decision:
                    type: string
                  details:
                    type: object
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  components:
                    type: array
                    items:
                      type: string
  /metrics:
    get:
      summary: System metrics
      responses:
        '200':
          description: Metrics data
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: number
  /audit:
    get:
      summary: Retrieve audit trail
      responses:
        '200':
          description: Audit trail records
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                    event:
                      type: string
                    details:
                      type: object
