# This file documents the required branch protection settings
# Configure these in: Repository Settings > Branches > Branch protection rules

# For 'main' branch:
# 
# Required status checks before merging:
#   ✓ Require status checks to pass before merging
#   ✓ Require branches to be up to date before merging
#   
#   Required checks:
#     - Type Safety & Linting
#     - Unit Tests
#     - EventBus Feature Tests
#     - TriggerMesh Tests
#     - Build Check
#     - CI Summary
#   
# Additional settings:
#   ✓ Require pull request reviews before merging (1 approval)
#   ✓ Dismiss stale pull request approvals when new commits are pushed
#   ✓ Require review from Code Owners
#   ✓ Include administrators
#   ✓ Allow force pushes: disabled
#   ✓ Allow deletions: disabled

name: Branch Protection Info
on: [workflow_dispatch]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Display protection info
      run: |
        echo "Branch Protection Configuration"
        echo "==============================="
        echo ""
        echo "To enable branch protection for 'main':"
        echo "1. Go to: Repository Settings > Branches"
        echo "2. Add rule for branch name pattern: main"
        echo "3. Enable:"
        echo "   - Require status checks to pass before merging"
        echo "   - Require branches to be up to date before merging"
        echo "4. Select required status checks:"
        echo "   - Type Safety & Linting"
        echo "   - Unit Tests"
        echo "   - EventBus Feature Tests"
        echo "   - TriggerMesh Tests"
        echo "   - Build Check"
        echo "   - CI Summary"
