name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: grace_test
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -p 5432 && break
            sleep 1
          done
      - name: Run migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/grace_test
        run: |
          psql "$DATABASE_URL" -f migrations/002_phase_a_core_tables.sql
          psql "$DATABASE_URL" -f migrations/003_phase_b_forensics_tables.sql
          psql "$DATABASE_URL" -f migrations/004_phase_c_learning_tables.sql
      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/grace_test
        run: |
          pytest -q
