name: KPI Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  kpi-tests:
    name: KPI Validation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: grace_test
          POSTGRES_PASSWORD: grace_test_pass
          POSTGRES_DB: grace_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pytest pytest-asyncio pytest-benchmark
    
    - name: Run KPI tests
      env:
        DATABASE_URL: postgresql://grace_test:grace_test_pass@localhost:5432/grace_test
        REDIS_URL: redis://localhost:6379
        ENVIRONMENT: testing
        AUTH_SECRET_KEY: test-secret-key-minimum-32-characters
      run: |
        pytest tests/test_kpis.py -v --tb=short
    
    - name: Performance benchmarks
      env:
        DATABASE_URL: postgresql://grace_test:grace_test_pass@localhost:5432/grace_test
        REDIS_URL: redis://localhost:6379
        ENVIRONMENT: testing
        AUTH_SECRET_KEY: test-secret-key-minimum-32-characters
      run: |
        pytest tests/test_performance.py -v --benchmark-only
    
    - name: Generate KPI report
      run: |
        python scripts/generate_kpi_report.py > kpi-report.json
    
    - name: Upload KPI report
      uses: actions/upload-artifact@v4
      with:
        name: kpi-report
        path: kpi-report.json
    
    - name: Check KPI thresholds
      run: |
        python scripts/check_kpi_thresholds.py kpi-report.json
