name: Grace Policy Validation

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  policy-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for changed files detection
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **/*.py
          **/*.js
          **/*.sh
          **/*.bat
          **/*.ps1
          Dockerfile*
          docker-compose*.yml
          requirements.txt
          *.yml
          *.yaml
    
    - name: Run policy validation
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "Running policy validation on changed files:"
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
        
        # Run Grace policy checker
        python -m grace.policy.ci_integration \
          --output policy-report.md \
          --verbose \
          ${{ steps.changed-files.outputs.all_changed_files }}
    
    - name: Upload policy report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: policy-report
        path: policy-report.md
    
    - name: Add policy:pass label
      if: github.event_name == 'pull_request' && success()
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ['policy:pass']
          });
    
    - name: Check policy status
      if: always()
      run: |
        if [ -f policy-report.md ]; then
          if grep -q "❌ \*\*FAILED\*\*" policy-report.md; then
            echo "::error::Policy validation failed. Check the policy report for details."
            exit 1
          else
            echo "::notice::Policy validation passed."
          fi
        else
          echo "::warning::No policy report generated."
        fi