name: Quick Check

on:
  pull_request:
  
jobs:
  quick:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-quick-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-quick-
          ${{ runner.os }}-pip-
    
    - name: Install minimal dependencies
      run: |
        pip install --upgrade pip
        pip install -e . --no-deps || true
        pip install pydantic pydantic-settings fastapi || true
    
    - name: Quick import test
      env:
        AUTH_SECRET_KEY: quick-test-secret-key-min-32-chars
      run: |
        python -c "import grace; print('✅ Grace imports')" || exit 1
        python -c "from grace.config import get_settings; print('✅ Config works')" || exit 1
        python -c "from grace.events.schema import GraceEvent; print('✅ Events work')" || exit 1
        
    - name: Check for obvious errors
      run: |
        python -m py_compile grace/**/*.py || echo "::warning::Some files have syntax errors"
      continue-on-error: true
