name: Quick Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Quick import check
      run: |
        python -c "import grace; print('✅ Grace imports successfully')"
        python -c "from grace.config import get_settings; print('✅ Config loads')"
        python -c "from grace.events.schema import GraceEvent; print('✅ Events import')"
        python -c "from grace.governance.engine import GovernanceEngine; print('✅ Governance imports')"
        python -c "from grace.trust.core import TrustCoreKernel; print('✅ Trust imports')"
    
    - name: Verify critical gaps script
      run: python scripts/fix_critical_gaps.py || true
    
    - name: Check for common issues
      run: |
        echo "Checking for dict-based event publishing..."
        grep -r "bus.publish({" grace/ || echo "✅ No dict-based events found"
        
        echo "Checking for missing async keywords..."
        python scripts/verify_install.py
