# Example GitHub Actions Workflow for Staged Promotion
# .github/workflows/staged-promotion.yml

name: Staged Promotion

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        run: |
          ./scripts/ci_security_checks.sh
          ./scripts/ci_coverage_check.sh
      - name: Build Docker Image
        run: docker build -t grace_api:latest .
      - name: Push to Dev Registry
        env:
          DEV_REGISTRY: ${{ secrets.DEV_REGISTRY }}
        run: docker push $DEV_REGISTRY/grace_api:latest

  promote-to-staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Manual Approval
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: ${{ secrets.STAGING_APPROVAL_URL }}
          method: 'POST'
        env:
          STAGING_APPROVAL_URL: ${{ secrets.STAGING_APPROVAL_URL }}
      - name: Deploy to Staging
        run: echo "Deploying to staging..."

  promote-to-prod:
    needs: promote-to-staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Manual Approval
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: ${{ secrets.PROD_APPROVAL_URL }}
          method: 'POST'
        env:
          PROD_APPROVAL_URL: ${{ secrets.PROD_APPROVAL_URL }}
      - name: Deploy to Production
        run: echo "Deploying to production..."
